config/routes.rb
Rails.application.routes.draw do
  resources :words
  root "words#index"
  get 'get_all_cards' => 'cards#all_cards'
end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def all_cards
    @cards = Word.all

    if @cards.count < 3
       store_call_words
    end

    respond_to do |format|
      format.json  { render :json => @cards}
    end
  end

  def store_call_words
    Word.create(:front => "ascertain" ,:back =>"выяснять").save
    Word.create(:front => "accessible",:back =>"доступный").save
    Word.create(:front => "requirements",:back =>"требования").save
    Word.create(:front => "mean",:back =>"иметь в виду").save
    Word.create(:front => "apply",:back =>"подать заявление").save
    Word.create(:front => "refers",:back =>"относиться").save
    Word.create(:front => "approve",:back =>"утверждать/одобрять").save
    Word.create(:front => "attend",:back =>"посещать/присутствовать").save
    Word.create(:front => "quality",:back =>"качественный").save
    Word.create(:front => "recreateal",:back =>"обновление").save
    Word.create(:front => "complete",:back =>"полный/законченый").save
    Word.create(:front => "mondatory",:back =>"обязательный").save
    Word.create(:front => "suspend",:back =>"приостановить").save
    Word.create(:front => "fail",:back =>"потерпеть неудачу").save
    Word.create(:front => "response",:back =>"ответ").save
    Word.create(:front => "request",:back =>"запрос").save
    Word.create(:front => "avoid",:back =>"избегать").save
    Word.create(:front => "equipped",:back =>"оборудованный").save
    Word.create(:front => "suggest",:back =>"предлогать").save
    Word.create(:front => "violation",:back =>"нарушение").save
    Word.create(:front => "destination",:back =>"пункт назначения").save
    Word.create(:front => "reach",:back =>"достич").save
    Word.create(:front => "additionaly",:back =>"дополнительно").save
    Word.create(:front => "toll",:back =>"плата за проезд").save
    Word.create(:front => "emergency flashes",:back =>"аварийные мигалки").save
    Word.create(:front => "to speed up",:back =>"ускорять").save
    Word.create(:front => "extra charge",:back =>"дополнительная плата").save
    Word.create(:front => "fare",:back =>"тариф").save
    Word.create(:front => "according",:back =>"в соответствии").save
    Word.create(:front => "torn",:back =>"порванный").save
    Word.create(:front => "unreadable",:back =>"нечитаемый").save
    Word.create(:front => "immediately",:back =>"немедленно").save
    Word.create(:front => "to involve",:back =>"вовлекать").save
    Word.create(:front => "error",:back =>"ошибка").save
    Word.create(:front => "duty",:back =>"на работе").save
    Word.create(:front => "fashion omnibus",:back =>"Карета/повозка").save
    Word.create(:front => "to negotiate",:back =>"договариваться").save
    Word.create(:front => "entire",:back =>"весь/целый").save
    Word.create(:front => "revoke",:back =>"онулировать/отзыавть").save
    Word.create(:front => "deny",:back =>"отказывать").save
    Word.create(:front => "statement",:back =>"утверждение/высказывание").save
    Word.create(:front => "to implement",:back =>"реализовывать").save
    Word.create(:front => "to relate",:back =>"относиться(к чему то)").save
    Word.create(:front => "nearest",:back =>"ближайший").save
    Word.create(:front => "intruduction",:back =>"введение").save
    Word.create(:front => "to divide",:back =>"делить").save
    Word.create(:front => "major",:back =>"основной").save
    Word.create(:front => "responsible",:back =>"ответственный").save
    Word.create(:front => "approximately",:back =>"приблезительно").save
    Word.create(:front => "probation",:back =>"испытательный срок").save
    Word.create(:front => "puddle",:back =>"лужа").save
    Word.create(:front => "tailgated",:back =>"не держать дистанцию").save
    Word.create(:front => "trip",:back =>"поездка").save
    Word.create(:front => "rest",:back =>"отдых").save
    Word.create(:front => "property",:back =>"имущество").save
    Word.create(:front => "to find",:back =>"искать").save
    Word.create(:front => "idling",:back =>"ожидание").save
    Word.create(:front => "trunk",:back =>"багажник").save
    Word.create(:front => "advice",:back =>"совет").save
    Word.create(:front => "almost",:back =>"почти").save
    Word.create(:front => "approach",:back =>"подход").save
    Word.create(:front => "ahead",:back =>"впереди").save
    Word.create(:front => "agree",:back =>"соглашаться").save
    Word.create(:front => "collect",:back =>"собирать").save
    Word.create(:front => "refuse",:back =>"отказать").save
    Word.create(:front => "solicit",:back =>"выпрашивать").save
    Word.create(:front => "make sure",:back =>"убедиться").save
    Word.create(:front => "flat rate",:back =>"фиксированный тариф").save
    Word.create(:front => "within",:back =>"в пределах").save
    Word.create(:front => "to surrender",:back =>"сдаваться").save
    Word.create(:front => "replacement",:back =>"замена").save
    Word.create(:front => "disorderly",:back =>"беспорядочный").save
    Word.create(:front => "to follow",:back =>"следовать").save
    Word.create(:front => "during",:back =>"в течении (времени)").save
    Word.create(:front => "available",:back =>"доступный/свободный").save
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:front, :back)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/cards/all_cards.haml
%h1 "WHATS UP!!!"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PapasCards
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/words/_form.html.haml
= simple_form_for(@word, html: { class: 'form-horizontal' }) do |f|
  - if @word.errors.any?
    #error_explanation
      %h2
        = pluralize(@word.errors.count, "error")
        prohibited this word from being saved:
      %ul
        - @word.errors.full_messages.each do |message|
          %li= message
  .row
    .col-sm-6.col-sm-offset-3
      = f.label "Create Card"
      %br/
      = f.text_field :front, class: "form-control"
      = f.label "TRANSLATION"
      %br/
      = f.text_field :back, class: "form-control"
    .col-sm-3
  %br/
  .row
    .col-sm-6.col-sm-offset-3
      = f.submit  "Submit", class: 'btn btn-success'
      = link_to 'Back', words_path, class: "btn btn-danger"

app/views/words/edit.html.haml
%br/
%br/
.col-sm-8.col-sm-offset-2
  .panel.panel-danger
    .panel-heading
      %h1.text-center Editing Card
    .panel-body
      = render 'form'

app/views/words/index.html.haml
%p#notice= notice
%h1.text-center List of All Cards
%br/
.text-center
  = link_to 'Add New Word', new_word_path, class: "btn btn-lg btn-success"
%br/
.row
  .col-sm-8.col-sm-offset-2
    %table.table.table-striped
      %thead
        %tr
          %th NUM
          %th WORD
          %th TRANSLATION
          %th ACTION
      %tbody
        - @words.each do |word|
          %tr
            %td= word.id
            %td= word.front
            %td= word.back
            %td
              =link_to 'Edit', edit_word_path(word), class: "btn btn-warning"
              =link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"
%br/

app/views/words/new.html.haml
%br/
%br/
.col-sm-8.col-sm-offset-2
  .panel.panel-success
    .panel-heading
      %h1.text-center New Card
    .panel-body
      = render 'form'

app/views/words/show.html.haml
%br/
%br/
%br/
.col-sm-6.col-sm-offset-3
  .panel.panel-default
    .panel-heading
      %h1 Show Card
    .panel-body
      %h3
        %strong Front Side:
        = @word.front
      %br/
      %h3
        %strong Back Side:
        = @word.back
    .panel-footer
      = link_to 'Edit', edit_word_path(@word), class: "btn btn-warning"
      = link_to 'All List', words_path, class: "btn btn-success"